apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello
          image: smith1984/otus_ms_scala:0.0.4
          ports:
            - name: web
              containerPort: 8083
          livenessProbe:
            httpGet:
              port: 8083
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8083
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: "/app/app.conf"
              subPath: "app.conf"
              readOnly: true
            - name: secret
              mountPath: "/app/secrets.conf"
              subPath: "secrets.conf"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: config-application
        - name: secret
          secret:
            secretName: secrets-application